stages:
  create-column-models:
    cmd: >
      python scripts/create_column_models.py 
      --data data/data.csv
      --output data/column_models.json
    deps:
      - scripts/create_column_models.py
      - data/data.csv
    outs:
      - data/column_models.json