plots:
- qc/cgpm-hydrated-dependence-probability.csv:
    template: resources/dependence_probability.json
    y: column1
    x: column2
- qc/marginals/1d_fits.csv:
    template: resources/marginal_fits.json
    y: Score
    x: idx
- qc/marginals/2d_fits.csv:
    template: resources/marginal_fits.json
    y: Score
    x: idx
- data/org_size_salary_remote.png
- data/anxiety_gender_sexuality.png

stages:
  preprocess:
    cmd: >
      poetry run preprocess
      --data data/data.csv
      --output data/preprocessed.csv
      --column_model_output data/column_models.json
      --sql "${sql_preprocessing}"
    deps:
    - data/data.csv
    outs:
    - data/preprocessed.csv
    - data/column_models.json

  loom-schema:
    cmd: >
      poetry run loom_schema
      --column_models data/column_models.json
      --output data/loom-schema.json
    deps:
    - data/column_models.json
    outs:
    - data/loom-schema.json

  loom-ingest:
    cmd: ./bin/loom_task ingest loom data/loom-schema.json data/preprocessed.csv
    deps:
    - data/loom-schema.json
    - data/preprocessed.csv
    outs:
    - loom/ingest
    - loom/query

  loom-infer-config:
    cmd: >
      yq -o=json '.loom' params.yaml
      > data/infer-config.json
    outs:
    - data/infer-config.json

  loom-infer:
    cmd: ./bin/loom_task infer loom ${sample_count} data/infer-config.json
    deps:
    - loom/ingest
    - loom/query
    - data/infer-config.json
    params:
    - sample_count
    outs:
    - loom/samples

  loom-sample:
    cmd: >
      ./bin/loom python scripts/loom_sample.py
      --sample_count ${qc.sample_count}
      --output data/synthetic-data-loom.csv
    deps:
    - loom/samples
    - scripts/loom_sample.py
    outs:
    - data/synthetic-data-loom.csv

  loom-to-json:
    cmd: >
      find loom/samples -type f ! -name '*.json' |
      parallel  "./bin/loom python scripts/loom_to_json.py loom_to_json {}"
    deps:
    - loom/samples

  loom-to-cgpm:
    cmd: >
      mkdir -p data/cgpm/hydrated &&
      ls loom/samples |
      parallel  "poetry run loom_to_cgpm
      --column_model_filename data/column_models.json
      --data_filename data/preprocessed.csv
      --loom_folder loom/samples/{}
      --out_filename data/cgpm/hydrated/{}.json"
    deps:
    - loom/samples
    - data/column_models.json
    - data/preprocessed.csv
    outs:
    - data/cgpm/hydrated

  cgpm-sample:
    foreach:
    - hydrated
    do:
      cmd: >
        poetry run cgpm-sample
        --sample_count ${qc.sample_count}
        --output data/synthetic-data-cgpm-${item}.csv
        --model_dir data/cgpm/${item}
        --data data/preprocessed.csv
      deps:
      - data/cgpm/${item}
      outs:
      - data/synthetic-data-cgpm-${item}.csv

  cgpm-to-sppl:
    cmd: >
      poetry run cgpm-to-sppl
      --output data/sppl/merged.json
      --model_dir data/cgpm/hydrated
      --data data/preprocessed.csv
    deps:
    - data/cgpm/hydrated
    outs:
    - data/sppl/merged.json

  sample-sppl:
    cmd: >
      poetry run sample-sppl
      --sample_count ${qc.sample_count}
      --output data/synthetic-data-sppl-hydrated.csv
      --model data/sppl/merged.json
      --data data/preprocessed.csv
    deps:
    - data/sppl/merged.json
    outs:
    - data/synthetic-data-sppl-hydrated.csv
  
  train-baseline:
    foreach:
    - ctgan
    - tvae
    do:
      cmd: >
        poetry run train-baseline
        --data data/preprocessed.csv
        --column_models data/column_models.json
        --model ${item}
      deps:
      - data/preprocessed.csv
      - data/column_models.json
      outs:
      - data/${item}.pkl

  sample-baseline:
    foreach:
    - ctgan
    - tvae
    do:
      cmd: >
        poetry run sample-baseline
        --model ${item}
        --sample_count ${qc.sample_count}
      deps:
        - data/${item}.pkl
      outs:
        - data/synthetic-data-${item}.csv

  marginal-fits:
    foreach:
    - loom
    - cgpm-hydrated
    - sppl-hydrated
    - ctgan
    - tvae
    do:
      cmd: >
        poetry run marginal_fits
        --real_data data/preprocessed.csv
        --model ${item}
        --column_models data/column_models.json
      deps:
      - data/preprocessed.csv
      - data/synthetic-data-${item}.csv
      outs:
      - qc/marginals/${item}_1d_fits.csv
      - qc/marginals/${item}_2d_fits.csv
      - qc/marginals/${item}_worst_1d_fit.png
      - qc/marginals/${item}_worst_2d_fit.png
      - qc/marginals/${item}_worst_1d_fit.html
      - qc/marginals/${item}_worst_2d_fit.html

  marginal-fits-plot:
    cmd: >
      poetry run marginal-fits-plot
      -m cgpm-raw
      -m ctgan
      -m tvae
    deps:
    - qc/marginals/ctgan_1d_fits.csv
    - qc/marginals/ctgan_2d_fits.csv
    - qc/marginals/cgpm-raw_1d_fits.csv
    - qc/marginals/cgpm-raw_2d_fits.csv
    outs:
    - qc/marginals/1d_fits.csv
    - qc/marginals/2d_fits.csv

  dependence-probability:
    foreach:
    - hydrated
    do:
      cmd: poetry run dependence-probability --model_dir data/cgpm/${item} --out_file
        qc/cgpm-${item}-dependence-probability.csv
      deps:
      - data/cgpm/${item}
      outs:
      - qc/cgpm-${item}-dependence-probability.csv