stages:
  validate-column-names:
    cmd: bin/validate.sh
    deps:
      - data/data.csv
    outs:
      - data/validated.csv

  nullify:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/nullify
      < data/validated.csv
      > data/nullified.csv
    deps:
      - data/validated.csv
    params:
      - nullify
    outs:
      - data/nullified.csv

  guess-schema:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/guess-schema
      < data/nullified.csv
      > data/schema.edn
    deps:
      - data/nullified.csv
    params:
      - schema
    outs:
      - data/schema.edn

  cgpm-schema:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/cgpm-schema
      < data/schema.edn
      > data/cgpm-schema.edn
    deps:
      - data/schema.edn
    outs:
      - data/cgpm-schema.edn

  ignore:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/ignore
      :schema '"data/schema.edn"'
      < data/nullified.csv
      > data/ignored.csv
    deps:
      - data/nullified.csv
      - data/schema.edn
    outs:
      - data/ignored.csv

  numericalize:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/numericalize
      :schema '"data/schema.edn"'
      :table data/mapping-table.edn
      < data/ignored.csv
      > data/numericalized.csv
    deps:
      - data/ignored.csv
      - data/schema.edn
    outs:
      - data/numericalized.csv
      - data/mapping-table.edn

  cgpm-generate-metadata:
    cmd: >
      mkdir -p data/cgpm/hydrated &&
      rm -f data/cgpm/inf.log &&
      seq 0 $(($(bin/param sample_count) - 1)) |
      parallel $(bin/param parallel.flags)
      'python scripts/cgpm_hydrate.py
      --output data/cgpm/hydrated/sample.{}.json
      --data data/numericalized.csv
      --schema data/cgpm-schema.edn
      --mapping-table data/mapping-table.edn
      --seed $(($(bin/param seed) + {#} - 1))'
    params:
      - parallel.flags
      - sample_count
      - seed
    deps:
      - data/cgpm-schema.edn
      - data/mapping-table.edn
      - data/numericalized.csv
      - schemas/cgpm.json
      - scripts/cgpm_hydrate.py
    outs:
      - data/cgpm/hydrated

  cgpm-infer-hyperparameters:
    cmd: >
      find data/cgpm/hydrated -type f |
      parallel jsonschema --instance {} schemas/cgpm.json &&
      mkdir -p data/cgpm/complete &&
      echo $(bin/param cgpm.minutes) >> data/cgpm/inf.log &&
      find data/cgpm/hydrated -type f |
      sort |
      parallel $(bin/param parallel.flags)
      'python scripts/cgpm_infer.py {}
      --kernel alpha
      --kernel view_alphas
      --kernel column_hypers
      --kernel rows
      --kernel columns
      --output data/cgpm/complete/{/}
      --seed $(($(bin/param seed) + {#} - 1))
      --minutes $(bin/param cgpm.minutes)'
      #--iterations $(bin/param cgpm.iterations)
    params:
      - parallel.flags
      - seed
      - cgpm.minutes
      #- cgpm.iterations
    deps:
      - data/cgpm/hydrated
      - schemas/cgpm.json
      - scripts/cgpm_infer.py
    outs:
      - data/cgpm/complete

  save-dependencies:
    cmd: >
      find data/cgpm/complete -type f |
      sort |
      xargs python scripts/dep_prob.py
      --data data/numericalized.csv
      --output data/dep-prob.json
    deps:
      - data/cgpm/complete
    outs:
      - data/dep-prob.json

  save-max-number-views:
    cmd: >
      find data/cgpm/complete -type f |
      xargs python scripts/save_n_views.py
      >> data/max-number-views.txt
    deps:
      - data/cgpm/complete
    outs:
      - data/max-number-views.txt


  dep-prob-vl:
    cmd: >
      clojure -X inferenceql.auto-modeling.heatmap/dep-prob :json-path '"data/dep-prob.json"'
      > data/dep-prob.vl.json
    deps:
      - data/dep-prob.json
    outs:
      - data/dep-prob.vl.json

  dep-prob-vg:
    cmd: >
      pnpm vl2vg
      < data/dep-prob.vl.json
      > data/dep-prob.vg.json
    deps:
      - data/dep-prob.vl.json
    outs:
      - data/dep-prob.vg.json

  dep-prob-svg:
    cmd: >
      pnpm vg2svg
      < data/dep-prob.vg.json
      > data/dep-prob.svg
    deps:
      - data/dep-prob.vg.json
    outs:
      - data/dep-prob.svg

  save-linear-stats:
    cmd: >
      python scripts/linear_stats.py
      --data data/ignored.csv
      --schema data/schema.edn
      --output data/linear-stats.json
    deps:
      - data/ignored.csv
      - data/schema.edn
      - scripts/linear_stats.py
    outs:
      - data/linear-stats.json

  compare-dep-prob-with-linear:
    desc: "Compares results from dependency probability with standard statistical tests"
    cmd: >
      python scripts/compare_deps.py
      --deps data/dep-prob.json
      --linear data/linear-stats.json
      >> data/qc-statistical-tests.txt
    deps:
      - data/dep-prob.json
      - data/linear-stats.json
    outs:
      - data/qc-statistical-tests.txt

  ast-export:
    desc: "Exports ASTs of the parametric model programs resulting from truncating CGPM-CrossCat models."
    cmd:
      - >-
        parallel ${parallel.flags}
        jsonschema --instance {} schemas/cgpm.json
        :::: <(find data/cgpm/complete -type f)
      - mkdir -p data/ast
      - >-
        parallel ${parallel.flags}
        'python scripts/ast_export.py
        --metadata {}
        --data data/numericalized.csv
        --mapping-table data/mapping-table.edn
        --output data/ast/{/.}.edn'
        :::: <(find data/cgpm/complete -type f)
    params:
      - parallel.flags
    deps:
      - data/cgpm/complete
      - data/ignored.csv
      - scripts/ast_export.py
    outs:
      - data/ast

  sppl-import:
    desc: "Imports a Multi-Mix AST and exports it AS a sum-product network"
    cmd:
      - mkdir -p data/sppl/unmerged
      - >-
        parallel ${parallel.flags}
        'python scripts/sppl_import.py
        --multi-mix-ast {}
        --max-number-views data/max-number-views.txt
        --output data/sppl/unmerged/{/.}.json'
        :::: <(find data/ast -type f)
    params:
      - parallel.flags
    deps:
      - data/ast
      - data/max-number-views.txt
      - scripts/sppl_import.py
    outs:
      - data/sppl/unmerged

  sppl-merge:
    desc: "Merges sum-product networks into a single network."
    cmd: >
      find data/sppl/unmerged -type f |
      sort |
      xargs python scripts/sppl_merge.py
      --output data/sppl/merged.json
    deps:
      - data/sppl/unmerged
    outs:
      - data/sppl/merged.json

  sppl-sample:
    cmd: >
      python scripts/sppl_sample.py
      --model data/sppl/merged.json
      --data data/ignored.csv
      --sample_count $(bin/param qc.sample_count)
      > qc/samples/samples-synthetic.edn
    deps:
      - data/sppl/merged.json
      - data/ignored.csv
    outs:
      - qc/samples/samples-synthetic.edn

  qc-tag-samples:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.samples/tag
      :data data/ignored.csv
      :samples-synthetic qc/samples/samples-synthetic.edn
      > qc/samples/samples.edn
    deps:
      - data/ignored.csv
      - qc/samples/samples-synthetic.edn
      - src/inferenceql/auto_modeling/qc/samples.clj
    outs:
      - qc/samples/samples.edn

  xcat-complete-import:
    desc: "Imports the final CGPM Crosscat samples as XCat records."
    cmd:
      - mkdir -p data/xcat/complete/
      - >-
        parallel ${parallel.flags}
        'clojure -X inferenceql.auto-modeling.xcat/import
        :cgpm-json {}
        :data-csv data/ignored.csv
        :mapping-table data/mapping-table.edn
        :numericalized-csv data/numericalized.csv
        :schema-edn data/schema.edn
        > data/xcat/complete/{/.}.edn'
        :::: <(find data/cgpm/complete -type f)
    params:
      - parallel.flags
    deps:
      - data/cgpm/complete
      - data/mapping-table.edn
      - data/ignored.csv
      - data/numericalized.csv
      - data/schema.edn
      - src/inferenceql/auto_modeling/xcat.clj
    outs:
      - data/xcat/complete/

  assemble-database:
    cmd: >
      clojure -M:exec inferenceql.auto-modeling.main assemble-database
      --table-name $(bin/param database.table_name)
      --table-path $(bin/param database.table_path)
      --model-name $(bin/param database.model_name)
      --model-path $(bin/param database.model_path)
      > data/db.edn
    params:
      - database.table_name
      - database.table_path
      - database.model_name
      - database.model_path
    deps:
      - data/nullified.csv
      - data/cgpm
      - data/xcat
    outs:
      - data/db.edn

  qc-dashboard-spec:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.dashboard/spec
      :samples qc/samples/samples.edn
      :schema data/schema.edn
      :correlation data/linear-stats.json
      > qc/specs/qc-dashboard.vl.json
    params:
      - qc.columns
    deps:
      - qc/samples/samples.edn
      - data/schema.edn
      - data/linear-stats.json
      - src/inferenceql/auto_modeling/qc/dashboard.clj
      - src/inferenceql/auto_modeling/qc/util.clj
    outs:
      - qc/specs/qc-dashboard.vl.json

  qc-dashboard-app:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.app/create
      :template qc/templates/index.html
      :spec qc/specs/qc-dashboard.vl.json
      :renderer canvas
      :title '"QC dashboard"'
      > qc/app/qc-dashboard.html
    deps:
      - qc/templates/index.html
      - qc/specs/qc-dashboard.vl.json
      - src/inferenceql/auto_modeling/qc/app.clj
    outs:
      - qc/app/qc-dashboard.html

  qc-splom-spec:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.splom/spec
      :samples qc/samples/samples.edn
      :schema data/schema.edn
      :correlation data/linear-stats.json
      > qc/specs/qc-splom.vl.json
    params:
      - qc.columns
    deps:
      - qc/samples/samples.edn
      - data/schema.edn
      - data/linear-stats.json
      - src/inferenceql/auto_modeling/qc/splom.clj
      - src/inferenceql/auto_modeling/qc/util.clj
    outs:
      - qc/specs/qc-splom.vl.json

  qc-splom-app:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.app/create
      :template qc/templates/index.html
      :spec qc/specs/qc-splom.vl.json
      :renderer canvas
      :title '"QC scatter plot matrix"'
      > qc/app/qc-splom.html
    deps:
      - qc/templates/index.html
      - qc/specs/qc-splom.vl.json
      - src/inferenceql/auto_modeling/qc/app.clj
    outs:
      - qc/app/qc-splom.html

  prepare-publish:
    cmd: >
      rm -rf publish-analysis-output/ &&
      git clone https://github.com/OpenIQL/inferenceql.analyses.git publish-analysis-output &&
      mkdir publish-analysis-output/analyses/${dataset_name}/ &&
      mkdir publish-analysis-output/html-pages/${dataset_name}/ &&
      cp params.yaml publish-analysis-output/analyses/${dataset_name}/params.yaml &&
      cp data/data.csv publish-analysis-output/analyses/${dataset_name}/data.csv &&
      cp data/schema.edn publish-analysis-output/analyses/${dataset_name}/schema.edn &&
      cp data/sppl/merged.json publish-analysis-output/analyses/${dataset_name}/merged.json &&
      touch publish-analysis-output/analyses/${dataset_name}/queries.iql &&
      cp qc/app/qc-dashboard.html publish-analysis-output/html-pages/${dataset_name}/qc-dashboard.html &&
      cp qc/app/qc-splom.html publish-analysis-output/html-pages/${dataset_name}/qc-splom.html &&
      cd publish-analysis-output && git checkout -b ${dataset_name}-to-publish && git add ./analyses/* && git add ./html-pages/* && git commit -m "automatic initial commit"
    deps:
      - data/data.csv
      - data/schema.edn
      - data/sppl/merged.json
      - qc/app/qc-splom.html
      - qc/app/qc-dashboard.html
    outs:
      - publish-analysis-output/analyses/${dataset_name}/
      - publish-analysis-output/html-pages/${dataset_name}/
