stages:
  nullify:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/nullify
      < data/data.csv
      > data/nullified.csv
    deps:
      - data/data.csv
    params:
      - nullify
    outs:
      - data/nullified.csv

  guess-schema:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/guess-schema
      < data/nullified.csv
      > data/schema.edn
    deps:
      - data/nullified.csv
    params:
      - schema
    outs:
      - data/schema.edn

  cgpm-schema:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/cgpm-schema
      < data/schema.edn
      > data/cgpm-schema.edn
    deps:
      - data/schema.edn
    outs:
      - data/cgpm-schema.edn

  ignore:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/ignore
      :schema '"data/schema.edn"'
      < data/data.csv
      > data/ignored.csv
    deps:
      - data/nullified.csv
      - data/schema.edn
    outs:
      - data/ignored.csv

  numericalize:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/numericalize
      :schema '"data/schema.edn"'
      :table data/mapping-table.edn
      < data/ignored.csv
      > data/numericalized.csv
    deps:
      - data/ignored.csv
      - data/schema.edn
    outs:
      - data/numericalized.csv
      - data/mapping-table.edn

  loom-schema:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/loom-schema
      < data/schema.edn
      > data/loom-schema.json
    deps:
      - data/schema.edn
    outs:
      - data/loom-schema.json

  loom-ingest:
    cmd: ./bin/loom_task ingest loom data/loom-schema.json data/numericalized.csv
    deps:
      - data/loom-schema.json
      - data/numericalized.csv
    outs:
      - loom/ingest
      - loom/query

  loom-infer-config:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/infer-config
      < params.yaml
      > data/infer-config.json
    params:
      - loom.extra_passes
      - seed
    outs:
      - data/infer-config.json

  loom-infer:
    cmd: ./bin/loom_task infer loom $(bin/param sample_count) data/infer-config.json
    deps:
      - loom/ingest
      - loom/query
      - data/infer-config.json
    params:
      - sample_count
    outs:
      - loom/samples

  loom-dump-metadata:
    cmd: >
      mkdir -p data/cgpm/raw &&
      find loom/samples -mindepth 1 -maxdepth 1 -type d |
      parallel $(bin/param parallel.flags)
      ./bin/loom python scripts/loom_dump.py {}
      --output data/cgpm/raw/{/}.json
    params:
      - parallel.flags
    deps:
      - loom/samples
      - scripts/loom_dump.py
    outs:
      - data/cgpm/raw

  cgpm-hydrate-metadata:
    cmd: >
      find data/cgpm/raw -type f |
      parallel jsonschema --instance {} schemas/cgpm.json &&
      mkdir -p data/cgpm/hydrated &&
      find data/cgpm/raw -type f |
      sort |
      parallel $(bin/param parallel.flags)
      'python scripts/cgpm_hydrate.py
      --metadata {}
      --output data/cgpm/hydrated/{/}
      --data data/numericalized.csv
      --schema data/cgpm-schema.edn
      --mapping-table data/mapping-table.edn
      --seed $(($(bin/param seed) + {#} - 1))'
    params:
      - parallel.flags
      - seed
    deps:
      - data/cgpm-schema.edn
      - data/cgpm/raw
      - data/mapping-table.edn
      - data/numericalized.csv
      - schemas/cgpm.json
      - scripts/cgpm_hydrate.py
    outs:
      - data/cgpm/hydrated

  # cgpm-generate-metadata:
  #   cmd: >
  #     mkdir -p data/cgpm/hydrated &&
  #     seq 0 $(($(bin/param sample_count) - 1)) |
  #     parallel $(bin/param parallel.flags)
  #     'python scripts/cgpm_hydrate.py
  #     --output data/cgpm/hydrated/sample.{}.json
  #     --data data/numericalized.csv
  #     --schema data/cgpm-schema.edn
  #     --mapping-table data/mapping-table.edn
  #     --seed $(bin/param seed)'
  #   params:
  #     - parallel.flags
  #     - sample_count
  #     - seed
  #   deps:
  #     - data/cgpm-schema.edn
  #     - data/mapping-table.edn
  #     - data/numericalized.csv
  #     - schemas/cgpm.json
  #     - scripts/cgpm_hydrate.py
  #   outs:
  #     - data/cgpm/hydrated

  cgpm-infer-hyperparameters:
    cmd: >
      find data/cgpm/hydrated -type f |
      parallel jsonschema --instance {} schemas/cgpm.json &&
      mkdir -p data/cgpm/complete &&
      find data/cgpm/hydrated -type f |
      sort |
      parallel $(bin/param parallel.flags)
      'python scripts/cgpm_infer.py {}
      --kernel alpha
      --kernel view_alphas
      --kernel column_hypers
      --output data/cgpm/complete/{/}
      --seed $(($(bin/param seed) + {#} - 1))
      --minutes $(bin/param cgpm.minutes)'
      #--iterations $(bin/param cgpm.iterations)
    params:
      - parallel.flags
      - seed
      - cgpm.minutes
      #- cgpm.iterations
    deps:
      - data/cgpm/hydrated
      - schemas/cgpm.json
      - scripts/cgpm_infer.py
    outs:
      - data/cgpm/complete

  save-dependencies:
    cmd: >
      find data/cgpm/complete -type f |
      sort |
      xargs python scripts/dep_prob.py
      --data data/numericalized.csv
      --output data/dep-prob.json
    deps:
      - data/cgpm/complete
    outs:
      - data/dep-prob.json

  save-correlations:
    cmd: >
      python scripts/correlation.py
      --data data/nullified.csv
      --schema data/schema.edn
      --output data/correlation.json
    deps:
      - data/nullified.csv
      - data/schema.edn
      - scripts/correlation.py
    outs:
      - data/correlation.json

  sppl-import:
    cmd: >
      find data/cgpm/complete -type f |
      parallel jsonschema --instance {} schemas/cgpm.json &&
      mkdir -p data/sppl/unmerged &&
      find data/cgpm/complete -type f |
      parallel $(bin/param parallel.flags)
      'python scripts/sppl_import.py
      --metadata {}
      --data data/numericalized.csv
      --mapping-table data/mapping-table.edn
      --output data/sppl/unmerged/{/}'
    params:
      - parallel.flags
    deps:
      - data/cgpm/complete
      - data/numericalized.csv
      - scripts/sppl_import.py
    outs:
      - data/sppl/unmerged

  sppl-merge:
    cmd: >
      find data/sppl/unmerged -type f |
      sort |
      xargs python scripts/sppl_merge.py
      --output data/sppl/merged.json
    deps:
      - data/sppl/unmerged
    outs:
      - data/sppl/merged.json

  sppl-sample:
    cmd: >
      python scripts/sppl_sample.py
      --model data/sppl/merged.json
      --data data/nullified.csv
      --sample_count $(bin/param qc.sample_count)
      > qc/samples/samples-virtual.edn
    deps:
      - data/sppl/merged.json
      - data/nullified.csv
    outs:
      - qc/samples/samples-virtual.edn

  iql-viz-schema:
    cmd: >
      clojure -X inferenceql.auto-modeling.main/iql-viz-schema
      < data/schema.edn
      > data/iql-schema.edn
    deps:
      - data/schema.edn
      - src/inferenceql/auto_modeling/main.clj
    outs:
      - data/iql-schema.edn

  qc-tag-samples:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.samples/tag
      :data data/nullified.csv
      :schema data/iql-schema.edn
      :samples-virtual qc/samples/samples-virtual.edn
      > qc/samples/samples.edn
    deps:
      - data/nullified.csv
      - data/iql-schema.edn
      - qc/samples/samples-virtual.edn
      - src/inferenceql/auto_modeling/qc/samples.clj
    outs:
      - qc/samples/samples.edn

  xcat-import:
    cmd: >
      mkdir -p data/xcat &&
      find data/cgpm/complete -type f |
      parallel $(bin/param parallel.flags)
      'clojure -X:xcat-import
      :cgpm-json {}
      :data-csv data/nullified.csv
      :mapping-table data/mapping-table.edn
      :numericalized-csv data/numericalized.csv
      :schema-edn data/iql-schema.edn
      > data/xcat/{/.}.edn'
    params:
      - parallel.flags
    deps:
      - data/cgpm/complete
      - data/mapping-table.edn
      - data/nullified.csv
      - data/numericalized.csv
      - data/iql-schema.edn
      - src/inferenceql/auto_modeling/xcat.clj
    outs:
      - data/xcat

  qc-dashboard-spec:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.dashboard/spec
      :samples qc/samples/samples.edn
      :schema data/iql-schema.edn
      :correlation data/correlation.json
      > qc/specs/qc-dashboard.vl.json
    params:
      - qc.columns
    deps:
      - qc/samples/samples.edn
      - data/iql-schema.edn
      - data/correlation.json
      - src/inferenceql/auto_modeling/qc/dashboard.clj
      - src/inferenceql/auto_modeling/qc/util.clj
    outs:
      - qc/specs/qc-dashboard.vl.json

  qc-dashboard-image:
    cmd: >
      yarn run vl2png
      -s $(bin/param qc.image_quality)
      -l warn
      qc/specs/qc-dashboard.vl.json
      qc/images/qc-dashboard.png
      2> qc/logs/vl2png-qc-image.log
    params:
      - qc.image_quality
    deps:
      - node_modules
      - qc/specs/qc-dashboard.vl.json
    outs:
      - qc/images/qc-dashboard.png
      - qc/logs/vl2png-qc-image.log

  qc-dashboard-app:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.app/create
      :template qc/templates/index.html
      :spec qc/specs/qc-dashboard.vl.json
      :renderer canvas
      :title '"QC dashboard"'
      > qc/app/qc-dashboard.html
    deps:
      - qc/templates/index.html
      - qc/specs/qc-dashboard.vl.json
      - src/inferenceql/auto_modeling/qc/app.clj
    outs:
      - qc/app/qc-dashboard.html

  qc-splom-spec:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.splom/spec
      :samples qc/samples/samples.edn
      :schema data/iql-schema.edn
      :correlation data/correlation.json
      > qc/specs/qc-splom.vl.json
    params:
      - qc.columns
    deps:
      - qc/samples/samples.edn
      - data/iql-schema.edn
      - data/correlation.json
      - src/inferenceql/auto_modeling/qc/splom.clj
      - src/inferenceql/auto_modeling/qc/util.clj
    outs:
      - qc/specs/qc-splom.vl.json

  qc-splom-image:
    cmd: >
      yarn run vl2png
      -s $(bin/param qc.image_quality)
      -l warn
      qc/specs/qc-splom.vl.json
      qc/images/qc-splom.png
      2> qc/logs/vl2png-qc-splom-image.log
    params:
      - qc.image_quality
    deps:
      - node_modules
      - qc/specs/qc-splom.vl.json
    outs:
      - qc/images/qc-splom.png
      - qc/logs/vl2png-qc-splom-image.log

  qc-splom-app:
    cmd: >
      clojure -X inferenceql.auto-modeling.qc.app/create
      :template qc/templates/index.html
      :spec qc/specs/qc-splom.vl.json
      :renderer canvas
      :title '"QC scatter plot matrix"'
      > qc/app/qc-splom.html
    deps:
      - qc/templates/index.html
      - qc/specs/qc-splom.vl.json
      - src/inferenceql/auto_modeling/qc/app.clj
    outs:
      - qc/app/qc-splom.html
