seed: 42
sample_count: 45
sub_sample:
  according_to_columns:
    year:
      - 2019
  N: 6053
parallel:
  # To limit the number of jobs GNU Parallel spawns use add the flag `--jobs n`.
  flags: >-
    --verbose
nullify:
  # Entries added here will be treated as null. For example, to treat "NaN" and
  # "missing" as null uncomment the following two lines:
  # - NaN
  # - missing
schema:
  # Key/value pairs can be added here to explicitly override the inferred schema
  # for each column. The available types are as follows: numerical, nominal, and ignore.
  # For example, to force the "age" column to be treated as a
  # numerical uncomment the following line:
  rakutenid: ignore
  year: ignore
  age: numerical
  household_composition_single: nominal
  household_composition_spouse: nominal
  household_composition_childrens_spouse: nominal
  household_composition_parents_of_spouse: nominal
  household_composition_children: nominal
  household_composition_childs_wife_or_son_in_law: nominal
  household_composition_grandchildren: nominal
  household_composition_your_siblings: nominal
  household_composition_spouse_siblings: nominal
  household_composition_other_relatives: nominal
  household_composition_non_relatives: nominal
  final_education_you: nominal
  final_education_spouse: nominal
  final_education_father: nominal
  final_education_mother: nominal
  current_working_status: nominal
  current_working_status_spouse: nominal
  current_working_status_father: nominal
  current_working_status_mother: nominal
  looking_for_a_job: nominal
  spouse_looking_for_a_job: nominal
  assets_such_as_houses_and_land: nominal
  balance_of_financial_assets: nominal
  current_mortgage_balance: nominal
  non_mortgage_debt: nominal
  big_five_extraverted_enthusiastic: nominal
  big_five_critical_quarrelsome: nominal
  big_five_dependable_self_disciplined: nominal
  big_five_anxious_easily_upset: nominal
  big_five_open_to_new_experiencescomplex: nominal
  big_five_reserved_quiet: nominal
  big_five_sympathetic_warm: nominal
  big_five_disorganized_careless: nominal
  big_five_calm_emotionally_stable: nominal
  big_five_conventional_uncreative: nominal
  gender: nominal
  pref: nominal
  region: nominal
  extraversion: nominal
  agreeableness: nominal
  conscientiousness: nominal
  neuroticism: nominal
  openness: nominal
  schooling: nominal
  spouse_schooling: nominal
  father_schooling: nominal
  mother_schooling: nominal
  income: nominal
  spouse_income: ignore
  hh_income: ignore
  hopeful_income: ignore
  hhsize: nominal
  children: nominal
  child_underprimary: nominal
  child_primary: nominal
  child_secondary: nominal
  child_university: nominal
  decision_making_invovles_durablegoods: nominal
  decision_making_invovles_dailygoods: nominal
  decision_making_invovles_invest: nominal
  values_intl: nominal
  values_energy: nominal
  values_eat: nominal
  values_product: nominal
  values_fairtrade: nominal
  values_work: nominal
  values_localgrown: nominal
  values_ac: nominal
  values_peace: nominal
  values_invest: nominal
loom:
  extra_passes: 100
cgpm:
  iterations: 1
  minutes: 1260
  #dependence:
  #  # While the CrossCat implementation in CGPM takes dependence constraints, doing so
  #  # throws a not-implemented-error. Hence, we apply a workaround:
  #  #   - Supply a map from a target column name to a list of column names.
  #  #   - Each column in said list gets moved to the target column's view.
  #  Users:
  #    - Purpose
  #  Launch_Site:
  #    - Type_of_Orbit
  ## Independence is un-directional. For two columns foo and bar, setting `foo: - bar`
  ## and `bar: - foo` has the identical effect.
  #independence:
  #  Perigee_km:
  #    - Class_of_Orbit
  #    - Apogee_km
  #  Apogee_km:
  #    - Class_of_Orbit
clojurecat:
  iterations: 150
qc:
  # Set this to the number of synthetic samples desired in QC plots.
  sample_count: 5000
  # Set this to specify the columns visualized in QC plots.
  # When not set, up to 8 columns--taken from the schema--will be visualized.
  # e.g. columns: ["foo", "bar", "baz"]
  columns: null
  # This limits the number of categories shown for categorical variables in
  # 2-dimensional QC plots. Set this to null for no limit.
  category_limit: 10
mi:
  configs:
    # Set MI configs here. If not set, the configs are chosen at random.
    # For example, to set the config for health_status.
    # health_status: ["c) Average", "b) Below average"]
synthetic_data_evaluation:
  # If target is not specified, a random target is chosen for prediction.
  #target: Apogee_km
  predictor: Random_forest # One of "Random_forest" or "GLM"
    #N: 10000 # Subsample held-out dataframe with 1000 samples
database:
  table_name: data
  table_path: data/nullified.csv
  model_name: baseline_model
  model_path: data/xcat/complete/sample.0.edn
  # model_path: data/xcat/merged.edn
  # model_path: data/sppl/merged.json
