sample_count: 10
sql_preprocessing: "SELECT * EXCLUDE (Body_Mass_Index) FROM data USING SAMPLE reservoir(20000 ROWS) REPEATABLE (123);"
loom:
  # loom config, see here for an example:
  # https://github.com/probcomp/loom/blob/master/loom/config.py
  schedule:
    extra_passes: 500
    checkpoint_period_sec: 3600
  kernels:
    cat:
      empty_group_count: 10
qc:
  # Set this to the number of synthetic samples desired in QC plots.
  sample_count: 20000