seed: 0
sample_count: 3
parallel:
  # To limit the number of jobs GNU Parallel spawns use add the flag `--jobs n`.
  flags: >
    --verbose
nullify:
  # Entries added here will be treated as null. For example, to treat "NaN" and
  # "missing" as null uncomment the following two lines:
  # - NaN
  # - missing
schema:
  # Key/value paris can be added here to explicitly override the inferred schema
  # for each column. For example, to force the "age" column to be treated as a
  # numerical uncomment the following line:
  # age: numerical
loom:
  extra_passes: 1
cgpm:
  #iterations: 1
  minutes: 1
