sample_count: 8
n_test: 2330
sql_preprocessing: "SELECT * FROM data"
loom:
  # loom config, see here for an example:
  # https://github.com/probcomp/loom/blob/master/loom/config.py
  schedule:
    extra_passes: 5000
    checkpoint_period_sec: 3600
  kernels:
    kind:
        empty_kind_count: 100
    cat:
      empty_group_count: 100
qc:
  # Set this to the number of synthetic samples desired in QC plots.
  sample_count: 10000
  discretization_quantiles: 5
  regression_formula: " genetic_recurrence_score ~ 
  age.cut([50, 65]) + 
  chemotherapy + 
  progesterone_receptor_status
  "
  # menopausal_status + 
  # genetic_recurrence_score.cut([10, 15, 20, 25]) + 
  # treatment_assignment + 
  # age.cut([50, 65]) + 
  # age.cut([50, 65]) : genetic_recurrence_score.cut([10, 15, 20, 25]) + 
  # menopausal_status : genetic_recurrence_score.cut([10, 15, 20, 25])"
