[tool.poetry]
name = "inferenceql-auto-modeling"
version = "0.1.0"
description = ""
authors = ["Zane Shelby <poetry@zane.io>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
cgpm = {git = "https://github.com/probcomp/cgpm", branch = "zane/hardcode-version"}
dvc = "^3.13.3"
sppl = {git = "https://github.com/joaoloula/sppl", branch = "permissive_versions"}
edn-format = "^0.7.5"
jsonschema = "^4.19.0"
matplotlib = "^3.7.2"
scikit-learn = "^1.3.0"
# specifying urls seem to be the only reliable/fast way to install pytorch with poetry, see https://github.com/python-poetry/poetry/issues/6409
torch = [
    {url = "https://download.pytorch.org/whl/cpu/torch-2.0.1%2Bcpu-cp310-cp310-linux_x86_64.whl", platform = "linux"},
    {url = "https://download.pytorch.org/whl/cpu/torch-2.0.1-cp310-none-macosx_11_0_arm64.whl", platform = "darwin"}
]
jinja2 = "^3.1.2" # constraint only here because otherwise poetry tries and fails to read a wildcard constraint
botocore = "^1.30"  # constraint only here to make poetry solving faster
sdv = {url = "https://files.pythonhosted.org/packages/67/54/f324c074538f57b564790512f08571dd7efc850123afb76b29bd43c7bf89/sdv-1.3.0-py2.py3-none-any.whl"}
kaleido = "0.2.1"
pytest = "^7.4.2"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
