[tool.poetry]
name = "inferenceql-auto-modeling"
version = "0.1.0"
description = ""
authors = ["Zane Shelby <poetry@zane.io>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
cgpm = {git = "https://github.com/probcomp/cgpm", branch = "zane/hardcode-version"}
dvc = "^3.13.3"
sppl = {git = "https://github.com/joaoloula/sppl", branch="permissive_versions"}
edn-format = "^0.7.5"
jsonschema = "^4.19.0"
matplotlib = "^3.7.2"
catboost = "^1.2"
scikit-learn = "^1.3.0"
dvc-s3 = "^2.23.0"
altair = "^5.0.1"
jupyter = "^1.0.0"
ipdb = "^0.13.13"
vl-convert-python = "^0.11.2"
torch = {version = "^2", source = "pytorch-cpu-src"}
torchvision = {version = "^0.15", source = "pytorch-cpu-src"}
torchaudio = {version = "^2", source = "pytorch-cpu-src"}
sdv = "^1.2.1"

[[tool.poetry.source]]
name = "pytorch-cpu-src"
url = "https://download.pytorch.org/whl/cpu"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
