== Installation

=== Dependencies

We rely on the Devenv package manager. Devenv takes care of all our dependencies; currently confirmed to be working on Ubuntu and Mac.

- On Ubuntu, follow steps 1 and 2 in https://devenv.sh/getting-started[this guide] to install nix and devenv.
- On MacOS, install Nix as described https://determinate.systems/posts/determinate-nix-installer[here] and follow step 2 in https://devenv.sh/getting-started[this guide] to install nix and devenv.

The minimum devenv  version is `1.0.0`.

Users need to https://nixos.wiki/wiki/Flakes#Enable_flakes[enable Nix Flakes].

Further, we require docker to be installed and to be runnable without `sudo`.
Installation instructions for Mac or Ubuntu are
https://docs.docker.com/engine/install/[here].

Then:

* If on Linux, run postinstall script: https://docs.docker.com/engine/install/linux-postinstall/
* Log in using credentials sufficient for probcomp’s Docker org:
 ** If on Linux run `docker login`
 ** If on Mac, open the Docker app GUI and log in with credentials
* Pull the Loom Docker image:
 ** Confirm you have access to view https://hub.docker.com/r/probcomp/inferenceql.loom
 ** Run `docker pull probcomp/inferenceql.loom`


=== Download structure-learning

Install from git
[source,bash]
----
git clone git@github.com:OpenGen/GenSQL.structure-learning.git
----

=== Start the devenv shell

To install modeling capabilities, go to the structure-learning directory:
[source,bash]
----
cd GenSQL.structure-learning
----
and enter a development shell that includes all the dependencies by running:
[source,bash]
----
nix develop
----
WARNING: On macOS, this step can take up to an hour. The reason is that certain dependencies get compiled from scratch. It will only be slow once. The second time you run the `devenv shell` command, it will succeed instantaneously.
