= Quickstart
Ulli Schaechtle <u.schaechtle@gmail.com>

== Overview

This is a quickstart guide to help you use the IQL structure-learning project to build your own
models on tabular data and query them. This guide starts with building a model from an example dataset.

== Installation

=== Dependencies

We rely on the Devenv package manager. Devenv takes care of all our dependencies; currently confirmed to be working on Ubuntu and Mac.

IMPORTANT: Updates to MacOS are known to cause issues with the Nix package manager that powers Devenv.

- Mac users need to first install the Nix package manager with https://determinate.systems/posts/determinate-nix-installer[this installer].  Then they need to execute step 3 and only step 3 https://devenv.sh/getting-started/[here], i.e. `nix-env -if https://install.devenv.sh/latest`.
- Ubuntu users can find instructions to install Devenv https://devenv.sh/getting-started/[here].

Further, we require docker to be installed and to be runnable without `sudo`.
Installation instructions for Mac or Ubuntu are
https://docs.docker.com/engine/install/[here].

Then,

* if on linux, run postinstall script: https://docs.docker.com/engine/install/linux-postinstall/
* login using credentials sufficient for probcomp’s Docker org:
 ** if on linux run `docker login`
 ** if on mac, open the Docker app GUI and log in with credentials
* Pull the Loom Docker image:
 ** Confirm you have access to view https://hub.docker.com/r/probcomp/inferenceql.loom
 ** Run `docker pull probcomp/inferenceql.loom`

=== Download structure-learning

Install from git
[source,bash]
----
git clone git@github.com:InferenceQL/inferenceql.structure-learning.git InferenceQL
----

=== Start the Nix shell

To install modeling capabilities, go to the structure-learning directory:
[source,bash]
----
cd InferenceQL
----
and enter a development shell that includes all the dependencies by running:
[source,bash]
----
devenv shell
----
WARNING: on MacOS, this step can take up to an hour. The reason is that certain dependencies get compiled from scratch. It will only be slow once. The second time you run the `devenv shell` command, it will succeed instantaneously.

=== Running structure-learning
Add a csv file:
[source,bash]
----
cp ~/foo/mydat.csv data/data.csv
----
Modify the `params.yaml` file as needed. And build default models:
[source,bash]
----
dvc repro
----

TIP: Check the automatically generated data schema in `data/schema.edn`. Does it look correct?
If not, see the section below on editing the schema generation.

Go to `qc/app/qc-dashboard.html` and open it with a web browser to check the quality.

You can improve the default models by further editing the `params.yaml` file.
See our xref:structure-learning::structure-learning.adoc[section on automated data
modeling].

TIP: Add columns you are particularly interested in to the `columns` section for quality control (see commented out example in the `params.yaml` file). That way, you can ensure that the model captures exactly what you care about.

If not, see the section below on editing the schema generation.

== Querying the model
There are different ways to query automatically built models from Python,
Clojure and JavaScript.
Checkout the https://github.com/InferenceQL/inferenceql.query[inferenceQL.query repository]
about how to query models and data.
