= Structure Learning
Ulli Schaechtle <u.schaechtle@gmail.com>

== Overview

This documentation will help you use the GenSQL structure-learning project to build your own models on tabular data. 
Once built, these models can be queried using a link:model-querying.adoc[variety of interfaces]. 

We recommend that you start with the link:quick-start.adoc[Quick Start Guide], then use the individual documents for 
remembering how to do steps later. The link:quick-start.adoc[Quick Start Guide] shows you how to start building a 
small model from a dataset you supply and incrementally increase the size and fidelity of the model, then share your 
results with the GenSQL team.

After following the Quick Start Guide you can review more advanced information about 
link:model-backends.adoc[different backends] for structure-learning.


== Documentation
link:quick-start.adoc[Quick Start Guide]

link:installation.adoc[Installation]

link:data-preparation.adoc[Data Preparation]

link:pipeline-configuration.adoc[Pipeline Configuration]

link:model-building.adoc[Model Building]

link:quality-control.adoc[Quality Control]

link:baseline-comparison.adoc[Baseline Comparison]

link:model-sharing.adoc[Model Sharing]

link:model-querying[Model Querying]

link:model-backends.adoc[Model Backends]

link:bug-reporting.adoc[Bug Reporting]
