name: Clojure lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Build developer environment
        run: env-run echo "Devshell built"

      - name: Lint files
        run: env-run clj-kondo --lint deps.edn src bin test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
