name: Clojure test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install devenv
        run: nix profile install tarball+https://install.devenv.sh/latest
        shell: sh

      - name: Build developer environment and run checks
        run: devenv ci

      - name: Run Clojure tests
        run: devenv shell clojure -X:test:clj-test

      - name: Run ClojureScript tests
        run: devenv shell clojure -M:test:cljs-test
