name: Clojure test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Build developer environment
        run: env-run echo "Devshell built"

      - name: Run Clojure tests
        run: env-run clojure -X:test:clj-test

      - name: Run ClojureScript tests
        run: env-run clojure -M:test:cljs-test
