name: commit-linter

on:
  pull_request:
  push:
    branches: [main]

jobs:
  commit-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install commitlint
        run: |
          env-run pnpm install --frozen-lockfile

      - name: Print versions
        run: |
          env-run 'git --version &&
            node --version &&
            pnpm --version &&
            pnpm exec commitlint --version'

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: env-run pnpm exec commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: env-run pnpm exec commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
