name: DVC repro w/ satellites data

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dvc-satellites:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Build developer environment
        run: ./bin/env-run echo "Devshell built"

      - name: Run Clojure tests
        run: |
          mkdir data || true
          cp test/satellites/data.csv data
          ./bin/env-run dvc repro
