name: Python tests
on:
  push:
    paths:
      - 'flake.nix'
      - 'flake.lock'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nix
        uses: cachix/install-nix-action@v16

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Nix shell
        run: nix develop -c bash -c ':'

      - name: Run CGPM tests
        run: nix develop -c python -m pytest --pyargs cgpm -k "not __ci_"

      - name: Run SPPL tests
        run: nix develop -c python -m pyteset --pyargs sppl
