name: Python tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache virtual environment
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ env.pythonLocation }}-${{ hashFiles('Makefile', 'requirements.txt') }}
      - name: Install automodeling
        run: make install
      - name: Run CGPM tests
        run: make cgpm-test
      - name: Run SPPL tests
        run: make sppl-test
