name: Python build

on:
  push:
    paths:
      - '.github/workflows/python-build-tests.yaml'
      - 'flake.nix'
      - 'devshell.nix'
      - 'pyproject.toml'
      - 'requirements.txt'

  pull_request:
    paths:
      - '.github/workflows/python-build-tests.yaml'
      - 'flake.nix'
      - 'devshell.nix'
      - 'pyproject.toml'
      - 'requirements.txt'

jobs:
  run-tests:
    strategy:
      matrix:
        # n.b. github actions macos runners are currently
        # not supporting python 3.10.12. If we upgrade python
        # we can resume these tests on mac, if we want to.
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Build developer environment
        run: env-run echo "Devshell built"

      - name: Run SPPL tests
        run: env-run python -m pytest --pyargs sppl
