name: Python lint
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nix
        uses: cachix/install-nix-action@v16

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Nix shell
        run: nix develop -c bash -c ':'

      - name: Run black
        run: nix develop -c black --check scripts
