name: Python tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.12
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install automodeling
        run: make install
      - name: Run CGPM tests
        run: make cgpm-test
      - name: Run SPPL tests
        run: make sppl-test
      - name: Run automodeling tests
        run: make auto-test
