name: Tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: 1.10.1.536
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install ws
        run: npm install ws
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run Clojure tests
        run: bin/kaocha --reporter documentation --plugin kaocha.plugin/profiling
      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v5"
        with:
          default: 3.6.4
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install automodeling
        run: make install
      - name: Run CGPM tests
        run: make cgpm-test
      - name: Run SPPL tests
        run: make sppl-test
      - name: Run automodeling tests
        run: make auto-test
